apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-job-creator
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - command: ["/bin/bash"]
        args:
        - -c
        - >-
            date;
            python /code/k8s-job-creator.py
        image: localhost:5000/k8s-job-creator:1.0
        name: generic
        resources: {}
      restartPolicy: Never
